spring:
  application:
    name: eureka-server
server:
  port: 8091
eureka:
  instance: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance}:8092/eureka